# Commands for using docker.

# Start:
# docker-compose up -d 
# docker-compose up -d --build

# Stop:
# docker stop redis tg-bot-sticker-go

version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  go:
    container_name: tg-bot-sticker-go
    build:
      context: .
    ports:
      - "8080:8080"